spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: from@gmail.com
    password: yourpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        ssl:
          trust: smtp.gmail.com
    debug: true
